service: terrain-tiler

provider:
  name: aws
  runtime: python3.6
  stage: production

  region: us-east-1

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource:
       - "arn:aws:s3:::elevation-tiles-prod/*"

  environment:
    GDAL_CACHEMAX: 512
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 536870912
    CPL_TMPDIR: "/tmp"
    GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
    CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".tif"

custom:
  apigwBinary:
    types:
      - '*/*'

plugins:
  - serverless-apigw-binary

package:
  artifact: package.zip

functions:
  app:
    handler: tiler.elevation.APP
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
